import Head from 'next/head'
import { Box, Heading, Text, Button, Container, Flex, Center, Spacer } from '@chakra-ui/react'
import Navbar from '../components/Navbar'

export default function Hero() {
  return (
    <Box  
    bgImage="url('/images/hero-v2@2x.png') !important"
    bgPosition='center'
    bgSize='cover'
    >
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Container maxW='1200px'>
        <Flex direction='column'>
        <Box>
          <Navbar/>
        </Box>
        <Spacer/>
        <Flex  height='100vh'>
          <Box pos='relative' top='100px'>
          <Heading width='450px' letterSpacing='2px' lineHeight='1.2' >
            <Box as='span' fontWeight='500' fontSize='50px'>Professional</Box> <br />
            cleaning services 
            in <span>SouthEast</span>
          </Heading>
          </Box>
        </Flex>
        </Flex>
      </Container>
    </Box>
  )
}
