import Head from 'next/head'
import { Box, Heading, Text, Button } from '@chakra-ui/react'

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
{/*         <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Roboto:wght@500;700;900&display=swap" rel="stylesheet"/> */}
      </Head>
      <Heading fontSize="4xl" color="tomato"> Hello world </Heading>
      <Button size="lg" colorScheme='teal' > follow </Button>
    </Box>
  )
}
