import Head from 'next/head'
import { Box, Heading, Text, Button,Container } from '@chakra-ui/react'
import Hero from '../components/Hero'
import Services from '../components/Services'
import About from '../components/About'

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Services/>
      <About />
    </Box>
  )
}
